# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Hidden imports needed for FastAPI, SQLAlchemy, and other dependencies
hidden_imports = [
    'fastapi',
    'uvicorn',
    'uvicorn.workers.base',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.protocols.websockets.websockets_impl',
    'uvicorn.lifespan.on',
    'uvicorn.lifespan.off',
    'uvicorn.loops.auto',
    'uvicorn.loops.asyncio',
    'uvicorn.logging',
    'sqlalchemy',
    'sqlalchemy.dialects.postgresql',
    'sqlalchemy.dialects.postgresql.psycopg2',
    'sqlalchemy.pool',
    'psycopg2',
    'psycopg2-binary',
    'pydantic',
    'pydantic_core',
    'passlib',
    'passlib.handlers.bcrypt',
    'python-jose',
    'python-multipart',
    'pillow',
    'numpy',
    'asyncpg',
    'email_validator',
    'bcrypt',
    'starlette',
    'starlette.applications',
    'starlette.middleware',
    'starlette.middleware.cors',
    'starlette.routing',
    'starlette.responses',
    'starlette.requests',
    'jose',
    'jose.jwt',
    'backend.server_postgresql_fully_optimized',
]

a = Analysis(
    ['backend/server_postgresql_fully_optimized.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('backend/*.py', 'backend'),
        ('.env', '.'),
    ],
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='pac_backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    cofile=None,
    icon=None,
)
